Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2010"

  config.vm.network "private_network", ip: "192.168.33.2"

  config.vm.provider "libvirt" do |vb|
     vb.cpus = 4
     vb.memory = 8192
  end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install nginx php-fpm -y
     apt-get install mysql-server mysql-client -y
     apt-get install git git-lfs
     apt-get update
     apt-get full-upgrade -y
     apt-get update

     cd /var/www
     rm html -R
     git clone https://github.com/GoalPioneers/prototype.datasharding.git www
  SHELL
end
