Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  config.vm.network "private_network", ip: "192.168.121.2"
  config.vm.synced_folder ".", "/var/www/html", :nfs => { :mount_options => ["dmode=777", "fmode=666"] }

  config.vm.provider "libvirt" do |vb|
     vb.cpus = 5
     vb.memory = 16384
  end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get full-upgrade -y
  SHELL
end
