name: Build Dependencies
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Setup PHP
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      # Setup of Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      #
      - name: build dependencies
        run: |
          cd code
          composer install
      # Cached Artefacts for PHP
      - name: archive production artefacts
        uses: actions/upload-artifact@v3
        with:
          name: composer-package-files
          path: |
            code/composer.json
            code/composer.lock
      - name: archive vendor modules
        uses: actions/upload-artifact@v3
        with:
          name: php-composer-vendors
          path: code/vendor